services:
  backend:
    image: task-management-backend:latest
    networks:
      - internal
    ports:
      - 3000:3000
    env_file:
      - .env.production
    depends_on:
      postgres_db:
        condition: service_healthy
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - internal
    env_file:
      - .env.production
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
    networks:
      - internal
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres_db:
        condition: service_healthy

networks:
  internal:


volumes:
  postgres_data:
