// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

const url = Deno.env.get("DATABASE_URL");

if (url == null) {
    throw new Error("Cannot find DATABASE_URL");
}

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
    },
    datasource: {
        url,
    },
});
